name: Server

on:
  workflow_dispatch:
  push:
    branches:
      - server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Execute command
      run: |
        curl -s ${{ secrets.URL }}

    - name: Finish steps
      run: |
        echo "finish!"
