name: Update

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: sakura

    steps:
    - name: Execute command
      run: |
        curl ${{ secrets.URL }}

    - name: Finish steps
      run: |
        echo "finish!"
