name: Update

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: shell

    steps:
    - name: Shell
      run: |
        echo "start!"
        
    - name: key
      run: |
        echo '${{ secrets.KEY }}'

    - name: Finish
      run: |
        echo "finish!"
