name: Update

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Shell
      run: |
        echo "start!"
        
    - shell: bash
      env:
        SUPER_SECRET: ${{ shell.KEY }}
      run: |
        echo "$SUPER_SECRET"

    - name: Finish
      run: |
        echo "finish!"
